=== carlosas/phpat/src/Test/Test.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="selector">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute type="xs:string" name="type" use="optional"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="classes">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="selector" maxOccurs="unbounded" minOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="excluding">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="selector" maxOccurs="unbounded" minOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="assert" type="xs:string">
    </xs:element>
    <xs:element name="rule">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="classes"/>
                <xs:element ref="excluding" minOccurs="0"/>
                <xs:element ref="assert"/>
                <xs:element ref="classes"/>
                <xs:element ref="excluding" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="name" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="test">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="rule" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== carlosas/phpat/tests-old/architecture/Test.xml
<?xml version="1.0" encoding="UTF-8" ?>
<test xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="https://raw.githubusercontent.com/carlosas/phpat/master/YAML/src/Test/Test.xsd">
    <rule name="testAssertionsImplementAssertionInterface">
        <classes>
            <selector type="havePath">Rule/Assertion/*</selector>
        </classes>
        <excluding>
            <selector type="haveClassName">PHPat\Rule\Assertion\*\MustNot*</selector>
            <selector type="havePath">Rule/Assertion/MatchResult.php</selector>
            <selector type="havePath">Rule/Assertion/AbstractAssertion.php</selector>
        </excluding>
        <assert>mustExtend</assert>
        <classes>
            <selector type="haveClassName">PHPat\Rule\Assertion\AbstractAssertion</selector>
        </classes>
    </rule>
    <rule name="testAssertionsDoNotDependOnVendors">
        <classes>
            <selector type="havePath">Rule/Assertion/*</selector>
        </classes>
        <assert>canOnlyDependOn</assert>
        <classes>
            <selector type="haveClassName">PHPat\*</selector>
            <selector type="haveClassName">Psr\*</selector>
        </classes>
    </rule>
</test>
